export const fakeData = [
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/samsung-TV.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/tecno-camon-20.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/washing-machine.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
  {
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/tablet.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
  },
];
