export const fakeData = [
  {
    id: "1",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 5,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: true,
  },
  {
    id: "2",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: true,
  },
  {
    id: "3",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: true,
  },
  {
    id: "4",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: false,
  },
  {
    id: "5",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/samsung-TV.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: true,
  },
  {
    id: "6",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/tecno-camon-20.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: false,
  },
  {
    id: "7",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 0,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: true,
  },
  {
    id: "8",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/washing-machine.png",
    ratings: 5,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: true,
  },
  {
    id: "9",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/iphone.png",
    ratings: 5,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: false,
  },
  {
    id: "10",
    name: "iPhone 13 High Quality White Case with Double-Sided MagSafe Compatible Wireless Charging",
    category: "Phone",
    displayImage: "/tablet.png",
    ratings: 5,
    currentprice: "120",
    oldprice: "150",
    discount: true,
    discountpercentage: "30",
    raterange: "120",
    currency: "$",
    activatenewprice: false,
  },
];
